workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # 在 Codemagic UI 中创建名为 "app_store_credentials" 的环境变量组
      # 包含: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      groups:
        - app_store_credentials
      vars:
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.huanyunApp" # 请确保这与你 Apple Developer 账号中的 Bundle ID 一致
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Clean build environment
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/usr/local/share/workspace/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com # 替换为你的邮箱，构建成功后会收到通知和下载链接
      # 如果你想直接发布到 TestFlight，可以取消下面的注释
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
